services:
  - type: web
    name: freeapi
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENROUTER_API_KEY
        value: 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
    plan: starter
